server:
  port: 8888
spring:
  application:
    name: ms-administracion-server-config

# Configuracion Local
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///C:/GalaxyTraining/Cursos/CURS-000437-Microservices/Proyecto/01.-Microservices/F01/ms-administracion-data-config
#          searchLocations: file:///C:/Users/Ale/Desktop/Galaxy/PROYECTO-CURS-000437/Microservices/ms-administracion-data-config


# Configuracion Cloud (git)
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/Alexandra9804/PROYECTO-CURS-000437.git
#          searchPaths: 01.-Microservices/F01/ms-administracion-data-config
#          username: ${USER_NAME}
#          password: ${USER_TOKEN}
#          default-label: master
#          cloneOnStart: true

management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true