server:
  port: 8081
spring:
  application:
    name: ms-negocio-gestion-vehiculos

  datasource:
    url: jdbc:mysql://localhost:3306/db_ms_vehiculos?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:8890
        instance:
          management-base-url: http://localhost:${server.port}
eureka:
  instance:
      hostname: localhost
      prefer-ip-address: false
      instance-id: ${spring.application.name}:${server.port}
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8889/eureka
      
management:
    endpoints:
        web:
            exposure:
                include: "*"
    health:
        readinessstate:
            enabled: true
        livenessstate:
            enabled: true
    endpoint:
        health:
            probes:
                enabled: true