apiVersion: v1
kind: Service
metadata:
  name: curs-000437-db-oracle-service
  labels:
    name: db-oracle
    app: srv-db-oracle
spec:
  type: NodePort
  ports:
    - name: oracle
      port: 1521
      targetPort: 1521
      nodePort: 31521
  selector:
    name: db-oracle
    app: srv-db-oracle
