apiVersion: apps/v1
kind: Deployment
metadata:
  name: curs-000437-db-oracle-deployment
  labels:
    app: srv-db-oracle
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db-oracle
      app: srv-db-oracle
  strategy:
    type: Recreate
  template:
    metadata:
      name: srv-db-oracle
      labels:
        name: db-oracle
        app: srv-db-oracle
    spec:
      containers:
        - name: oracle
          image: gvenzl/oracle-xe:21-slim
          ports:
            - containerPort: 1521
              name: oracle
          env:
            - name: ORACLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: curs-000437-oracle-user-secret
                  key: oraclePassword
            - name: APP_USER
              valueFrom:
                secretKeyRef:
                  name: curs-000437-oracle-user-secret
                  key: oracleUsername
            - name: APP_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: curs-000437-oracle-user-secret
                  key: oraclePassword
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "500m"
              memory: 2Gi
          volumeMounts:
            - name: oracle-data
              mountPath: /opt/oracle/oradata
      volumes:
        - name: oracle-data
          emptyDir: {}
