apiVersion: v1
kind: Service
metadata:
  name: curs-000437-ms-negocio-gestion-clientes-service
  labels:
    app: ms-negocio-gestion-clientes
spec:
  type: LoadBalancer
  selector:
    app: ms-negocio-gestion-clientes
  ports:
    - name: http
      port: 8082
      targetPort: 8082
